version: '3.8'

services:
  svelte_colochation_dev:
    depends_on:
      - spring-colochation-api
    build:
      dockerfile: ./Dockerfile
      target: dev
    image: colochation:0.0.1
    restart: unless-stopped
    ports:
      - '5001:3000'
    environment:
      ORIGIN: 'http://localhost:3000'
      PUBLIC_API_BASE_URL: 'http://spring-colochation-api:8080' #  docker compose service's name as the host
    networks:
      - colochation

  spring-colochation-api:
    build:
      context: ../colochation-back
      dockerfile: ../colochation-back/Dockerfile
      target: runner
    image: colochation-api:0.0.1
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - colochation

networks:
  colochation:
    driver: bridge
