version: '3.8'

services:
  svelte_colochation_dev:
    build:
      dockerfile: ./Dockerfile
      target: dev
    image: colochation:0.0.1
    restart: unless-stopped
    ports:
      - '5001:3000'
    environment:
      ORIGIN: 'http://localhost:3000'
      PUBLIC_API_BASE_URL: 'http://localhost:8080'
    networks:
      - colochation

networks:
  colochation:
    driver: bridge
